apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-parameters
spec:
  minReadySeconds: 0
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 4800
  replicas: 2
  selector:
    matchLabels:
      app: my-amazing-app
  template:
    metadata:
      labels:
        app: my-amazing-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
