apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: my-amazing-app
  template:
    metadata:
      labels:
        app: my-amazing-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
